/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAccountPurgeRouteImport } from './routes/api.account-purge'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResetRouteImport } from './routes/_authenticated/reset'
import { Route as AuthenticatedRecentreRouteImport } from './routes/_authenticated/recentre'
import { Route as AuthenticatedPlaybookRouteImport } from './routes/_authenticated/playbook'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedPaperRouteImport } from './routes/_authenticated/paper'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedNotebookRouteImport } from './routes/_authenticated/notebook'
import { Route as AuthenticatedEdgeDiscoveryRouteImport } from './routes/_authenticated/edge-discovery'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedRecentreIndexRouteImport } from './routes/_authenticated/recentre.index'
import { Route as AuthenticatedRecentreStateRouteImport } from './routes/_authenticated/recentre.$state'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountPurgeRoute = ApiAccountPurgeRouteImport.update({
  id: '/api/account-purge',
  path: '/api/account-purge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResetRoute = AuthenticatedResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecentreRoute = AuthenticatedRecentreRouteImport.update({
  id: '/recentre',
  path: '/recentre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaybookRoute = AuthenticatedPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaperRoute = AuthenticatedPaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotebookRoute = AuthenticatedNotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEdgeDiscoveryRoute =
  AuthenticatedEdgeDiscoveryRouteImport.update({
    id: '/edge-discovery',
    path: '/edge-discovery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecentreIndexRoute =
  AuthenticatedRecentreIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecentreRoute,
  } as any)
const AuthenticatedRecentreStateRoute =
  AuthenticatedRecentreStateRouteImport.update({
    id: '/$state',
    path: '/$state',
    getParentRoute: () => AuthenticatedRecentreRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/edge-discovery': typeof AuthenticatedEdgeDiscoveryRoute
  '/notebook': typeof AuthenticatedNotebookRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/paper': typeof AuthenticatedPaperRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/recentre': typeof AuthenticatedRecentreRouteWithChildren
  '/reset': typeof AuthenticatedResetRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/api/account-purge': typeof ApiAccountPurgeRoute
  '/recentre/$state': typeof AuthenticatedRecentreStateRoute
  '/recentre/': typeof AuthenticatedRecentreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/edge-discovery': typeof AuthenticatedEdgeDiscoveryRoute
  '/notebook': typeof AuthenticatedNotebookRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/paper': typeof AuthenticatedPaperRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/reset': typeof AuthenticatedResetRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/api/account-purge': typeof ApiAccountPurgeRoute
  '/recentre/$state': typeof AuthenticatedRecentreStateRoute
  '/recentre': typeof AuthenticatedRecentreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/edge-discovery': typeof AuthenticatedEdgeDiscoveryRoute
  '/_authenticated/notebook': typeof AuthenticatedNotebookRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/paper': typeof AuthenticatedPaperRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/playbook': typeof AuthenticatedPlaybookRoute
  '/_authenticated/recentre': typeof AuthenticatedRecentreRouteWithChildren
  '/_authenticated/reset': typeof AuthenticatedResetRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRoute
  '/api/account-purge': typeof ApiAccountPurgeRoute
  '/_authenticated/recentre/$state': typeof AuthenticatedRecentreStateRoute
  '/_authenticated/recentre/': typeof AuthenticatedRecentreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/accounts'
    | '/analytics'
    | '/community'
    | '/dashboard'
    | '/edge-discovery'
    | '/notebook'
    | '/notes'
    | '/paper'
    | '/people'
    | '/playbook'
    | '/recentre'
    | '/reset'
    | '/settings'
    | '/trades'
    | '/api/account-purge'
    | '/recentre/$state'
    | '/recentre/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/accounts'
    | '/analytics'
    | '/community'
    | '/dashboard'
    | '/edge-discovery'
    | '/notebook'
    | '/notes'
    | '/paper'
    | '/people'
    | '/playbook'
    | '/reset'
    | '/settings'
    | '/trades'
    | '/api/account-purge'
    | '/recentre/$state'
    | '/recentre'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/accounts'
    | '/_authenticated/analytics'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/edge-discovery'
    | '/_authenticated/notebook'
    | '/_authenticated/notes'
    | '/_authenticated/paper'
    | '/_authenticated/people'
    | '/_authenticated/playbook'
    | '/_authenticated/recentre'
    | '/_authenticated/reset'
    | '/_authenticated/settings'
    | '/_authenticated/trades'
    | '/api/account-purge'
    | '/_authenticated/recentre/$state'
    | '/_authenticated/recentre/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiAccountPurgeRoute: typeof ApiAccountPurgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account-purge': {
      id: '/api/account-purge'
      path: '/api/account-purge'
      fullPath: '/api/account-purge'
      preLoaderRoute: typeof ApiAccountPurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reset': {
      id: '/_authenticated/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof AuthenticatedResetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recentre': {
      id: '/_authenticated/recentre'
      path: '/recentre'
      fullPath: '/recentre'
      preLoaderRoute: typeof AuthenticatedRecentreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbook': {
      id: '/_authenticated/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AuthenticatedPlaybookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paper': {
      id: '/_authenticated/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof AuthenticatedPaperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notebook': {
      id: '/_authenticated/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof AuthenticatedNotebookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edge-discovery': {
      id: '/_authenticated/edge-discovery'
      path: '/edge-discovery'
      fullPath: '/edge-discovery'
      preLoaderRoute: typeof AuthenticatedEdgeDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recentre/': {
      id: '/_authenticated/recentre/'
      path: '/'
      fullPath: '/recentre/'
      preLoaderRoute: typeof AuthenticatedRecentreIndexRouteImport
      parentRoute: typeof AuthenticatedRecentreRoute
    }
    '/_authenticated/recentre/$state': {
      id: '/_authenticated/recentre/$state'
      path: '/$state'
      fullPath: '/recentre/$state'
      preLoaderRoute: typeof AuthenticatedRecentreStateRouteImport
      parentRoute: typeof AuthenticatedRecentreRoute
    }
  }
}

interface AuthenticatedRecentreRouteChildren {
  AuthenticatedRecentreStateRoute: typeof AuthenticatedRecentreStateRoute
  AuthenticatedRecentreIndexRoute: typeof AuthenticatedRecentreIndexRoute
}

const AuthenticatedRecentreRouteChildren: AuthenticatedRecentreRouteChildren = {
  AuthenticatedRecentreStateRoute: AuthenticatedRecentreStateRoute,
  AuthenticatedRecentreIndexRoute: AuthenticatedRecentreIndexRoute,
}

const AuthenticatedRecentreRouteWithChildren =
  AuthenticatedRecentreRoute._addFileChildren(
    AuthenticatedRecentreRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEdgeDiscoveryRoute: typeof AuthenticatedEdgeDiscoveryRoute
  AuthenticatedNotebookRoute: typeof AuthenticatedNotebookRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPaperRoute: typeof AuthenticatedPaperRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedPlaybookRoute: typeof AuthenticatedPlaybookRoute
  AuthenticatedRecentreRoute: typeof AuthenticatedRecentreRouteWithChildren
  AuthenticatedResetRoute: typeof AuthenticatedResetRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEdgeDiscoveryRoute: AuthenticatedEdgeDiscoveryRoute,
  AuthenticatedNotebookRoute: AuthenticatedNotebookRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPaperRoute: AuthenticatedPaperRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedPlaybookRoute: AuthenticatedPlaybookRoute,
  AuthenticatedRecentreRoute: AuthenticatedRecentreRouteWithChildren,
  AuthenticatedResetRoute: AuthenticatedResetRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiAccountPurgeRoute: ApiAccountPurgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
